var Dua = "In the name of Allah, The Most Gracious and The Most Mercifulِ";
console.log(Dua);
var myName = "Aamir Khan Channa";
console.log(myName);
var myAge = 25;
console.log(myAge);
var favouriteColor = "Black";
console.log(favouriteColor);
favouriteColor = "White";
console.log(favouriteColor);
var married = true;
console.log(married);
var learning = "https://linktr.ee/giaic";
console.log(learning);
var faceBook = "https://www.facebook.com/aamirkhanchannaa/";
console.log(faceBook);
var instagram = "https://www.instagram.com/aamirkhanchanna/";
console.log(instagram);
var twitter = "https://twitter.com/aamirkhanchanna/";
console.log(twitter);
var linkdenIn = "https://www.linkedin.com/in/aamirkhanchanna/";
console.log(linkdenIn);
var gitHub = "https://github.com/aamirkhanchanna/";
console.log(gitHub);
var discord = "https://discord.com/channels/@meaamirkhanchanna";
console.log(discord);
var email = "aamirkhanchanna@yahoo.com";
console.log(email);
var cellNumber = "+923005044416";
console.log(cellNumber);
